# This workflow uses Flyway Hub to test the Flyway database migrations in the 'pagila' path(s).
#
# The workflow will run automatically against all pull requests that modify files under 'pagila'.
#
# It will also run on all pushes to 'main' that modify files under 'pagila'.
#
# In order to use this workflow you will need to create a Github Actions secret called
# FLYWAY_HUB_ACCESS_TOKEN containing a valid Flyway Hub API access token.
#
name: Database Migration Tests with Flyway

on:
  push:
    branches:
    - 'main'
    paths:
      - 'pagila/**'
  pull_request:
    paths:
    - 'pagila/**'
  workflow_dispatch: {}

jobs:
  test-migrations:
    name: Test flyway migration scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@v2
      - name: Test migrations on Flyway Hub
        uses: red-gate/flyway-hub-migration-test@v2
        with:
          projectName: redgate-test
          engine: PostgreSQL (v13.2)
          migrationDirs: pagila 
          flywayConfPath: flyway.conf  
env:
  FLYWAYHUB_ACCESS_TOKEN: ${{ secrets.FLYWAY_HUB_ACCESS_TOKEN }}
